<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../OutlookMailAdviser.Application/OutlookMailAdviser.Application.csproj" />
    <ProjectReference Include="../OutlookMailAdviser.Domain/OutlookMailAdviser.Domain.csproj" />
  </ItemGroup>

</Project>
